version: '3.9'

services:

  fusionauth:
    image: fusionauth/fusionauth-app:latest

    environment:
      DATABASE_URL: jdbc:postgresql://${FA_DATABASE_HOST}/${FA_DATABASE_NAME}

      DATABASE_USERNAME: ${FA_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${FA_DATABASE_PASSWORD}

      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database

    restart: unless-stopped

    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

volumes:
  fa_config: null
