# Generated by Django 4.0.1 on 2022-01-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordless_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
